version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout 

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout


workflows:
  circleci-pipeline-workflow:
    jobs:
      - build
      - test
  